[tool.poetry]
name = "vemmio-client"
version = "0.1.0"
description = ""
authors = ["vmmgu <vmmgu@proton.me>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
