# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vemmio_client/flood.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19vemmio_client/flood.proto\x12\x08vemmiopb\"X\n\x0b\x46loodReport\x12*\n\x05state\x18\x01 \x01(\x0e\x32\x1b.vemmiopb.FloodReport.State\"\x1d\n\x05State\x12\t\n\x05\x43LEAR\x10\x00\x12\t\n\x05\x46LOOD\x10\x01\x42=\n-com.vemmio.ha.integration.vemmio.rpc.vemmiopbP\x01Z\n./vemmiopbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vemmio_client.flood_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n-com.vemmio.ha.integration.vemmio.rpc.vemmiopbP\001Z\n./vemmiopb'
  _FLOODREPORT._serialized_start=39
  _FLOODREPORT._serialized_end=127
  _FLOODREPORT_STATE._serialized_start=98
  _FLOODREPORT_STATE._serialized_end=127
# @@protoc_insertion_point(module_scope)
